## These DNS records are created on an activedirectory-integrated DNS server
## This is just an example of how to create the records using PS for my "green" lab's management network.
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'jump.green' -IPv4Address '10.45.0.5' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'carbon-black-appliance.green' -IPv4Address '10.45.0.86' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'dsm-db-pool0.green' -IPv4Address '10.45.0.' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'dsm-db-pool1.green' -IPv4Address '10.45.0.' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'dsm-db-pool2.green' -IPv4Address '10.45.0.' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'dsm-db-pool3.green' -IPv4Address '10.45.0.' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'dsm-db-pool4.green' -IPv4Address '10.45.0.' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'dsm-db-pool5.green' -IPv4Address '10.45.0.' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'dsm-db-pool6.green' -IPv4Address '10.45.0.' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'dsm-db-pool7.green' -IPv4Address '10.45.0.' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'dsm-db-pool8.green' -IPv4Address '10.45.0.' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'dsm-db-pool9.green' -IPv4Address '10.45.0.' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'logs.green' -IPv4Address '10.45.0.160' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'logs01.green' -IPv4Address '10.45.0.161' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'vsan-fs1.green' -IPv4Address '10.45.0.162' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'vsan-fs2.green' -IPv4Address '10.45.0.163' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'vsan-fs3.green' -IPv4Address '10.45.0.164' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'vsan-fs4.green' -IPv4Address '10.45.0.165' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'supervisor-cp1.green' -IPv4Address '10.45.0.191' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'supervisor-cp2.green' -IPv4Address '10.45.0.192' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'supervisor-cp3.green' -IPv4Address '10.45.0.193' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'supervisor-cp4.green' -IPv4Address '10.45.0.194' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'supervisor-cp5.green' -IPv4Address '10.45.0.195' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'dsm.green' -IPv4Address '10.45.0.196' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'w01-pr.green' -IPv4Address '10.45.0.198' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'qs.green' -IPv4Address '10.45.0.199' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'vc01.green' -IPv4Address '10.45.0.200' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx01.green' -IPv4Address '10.45.0.201' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx02.green' -IPv4Address '10.45.0.202' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx03.green' -IPv4Address '10.45.0.203' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx04.green' -IPv4Address '10.45.0.204' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx05.green' -IPv4Address '10.45.0.205' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx06.green' -IPv4Address '10.45.0.206' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx07.green' -IPv4Address '10.45.0.207' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx08.green' -IPv4Address '10.45.0.208' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx09.green' -IPv4Address '10.45.0.209' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx10.green' -IPv4Address '10.45.0.210' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx11.green' -IPv4Address '10.45.0.211' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx12.green' -IPv4Address '10.45.0.212' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx13.green' -IPv4Address '10.45.0.213' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx14.green' -IPv4Address '10.45.0.214' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx15.green' -IPv4Address '10.45.0.215' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx16.green' -IPv4Address '10.45.0.216' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx17.green' -IPv4Address '10.45.0.217' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'esx18.green' -IPv4Address '10.45.0.218' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'fleetlcm.green' -IPv4Address '10.45.0.220' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'ops01.green' -IPv4Address '10.45.0.221' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'collector.green' -IPv4Address '10.45.0.222' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'vsp01.green' -IPv4Address '10.45.0.223' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'auto.green' -IPv4Address '10.45.0.224' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'auto-platform.green' -IPv4Address '10.45.0.225' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'sddcm.green' -IPv4Address '10.45.0.226' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'shared01.green' -IPv4Address '10.45.0.227' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'vidb.green' -IPv4Address '10.45.0.228' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'license.green' -IPv4Address '10.45.0.229' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'nsx01.green' -IPv4Address '10.45.0.230' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'nsx02.green' -IPv4Address '10.45.0.231' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'w01-vc.green' -IPv4Address '10.45.0.232' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'w01-nsx.green' -IPv4Address '10.45.0.233' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'w01-nsx-1.green' -IPv4Address '10.45.0.234' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'w01-nsx-e1.green' -IPv4Address '10.45.0.235' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'w01-nsx-e2.green' -IPv4Address '10.45.0.236' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'pixie.green' -IPv4Address '10.45.0.250' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'vlr-connector.green' -IPv4Address '10.45.0.239' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'build-dhcp01.green' -IPv4Address '10.45.0.240' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'build-dhcp02.green' -IPv4Address '10.45.0.241' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'build-dhcp03.green' -IPv4Address '10.45.0.242' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'build-dhcp04.green' -IPv4Address '10.45.0.243' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'build-dhcp05.green' -IPv4Address '10.45.0.244' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'build-dhcp06.green' -IPv4Address '10.45.0.245' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'build-dhcp07.green' -IPv4Address '10.45.0.246' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'build-dhcp08.green' -IPv4Address '10.45.0.247' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'build-dhcp09.green' -IPv4Address '10.45.0.248' -CreatePtr
Add-DnsServerResourceRecordA -ComputerName 'YOUR-DNS-SERVER-FQDN' -ZoneName 'YOUR-LAB-ZONE' -name 'build-dhcp10.green' -IPv4Address '10.45.0.249' -CreatePtr